version: '3.8'

services:
  registry:
    image: registry:2
    container_name: docker_registry
    ports:
      - "5000:5000" # Exposes the registry on port 5000
    volumes:
      - ./data:/var/lib/registry # Persists registry data in the local ./data directory
    restart: always # Automatically restart the container if it stops or system reboots
